"""Setup-time receiver-model resolution for Universal Remote."""

from enum import Enum
from importlib import import_module
from inspect import signature
import logging
from typing import cast

from infrared_protocols.commands import Command

from .infrared_library import (
    INFRARED_LIBRARY_CODESETS,
    infrared_library_codeset_receiver_decoder_id,
)
from .protocols.base import CommandMatchKey, ReceiveProtocolHandler
from .protocols.registry import PROTOCOL_REGISTRY
from .resolved import ResolvedReceiverModel

EVENT_UNKNOWN = "unknown"

_LOGGER = logging.getLogger(__name__)


def command_event_type(command_name: str) -> str:
    """Return the event type for one normalized command name."""
    return command_name.lower()


def receiver_event_types_for_codeset(codeset_id: str) -> list[str]:
    """Return received-command event types exposed by a receiver codeset."""
    return list(resolve_receiver_model(codeset_id).event_types)


def resolve_receiver_model(codeset_id: str) -> ResolvedReceiverModel:
    """Resolve immutable receive-side bindings for one configured remote."""
    decoder_id = infrared_library_codeset_receiver_decoder_id(codeset_id)
    handlers = _handlers_for_decoder(decoder_id)
    event_types = {EVENT_UNKNOWN}
    match_maps: dict[str, dict[CommandMatchKey, str]] = {}

    if handlers:
        event_types.update(handler.protocol_id for handler in handlers)
        event_types.update(
            handler.repeat_event_type
            for handler in handlers
            if handler.repeat_event_type is not None
        )

        enum_cls = _load_codeset_enum(codeset_id)
        if enum_cls is not None:
            match_maps = {
                handler.protocol_id: _build_codeset_match_map(enum_cls, handler)
                for handler in handlers
            }
            event_types.update(
                command_event_type(command_name)
                for match_map in match_maps.values()
                for command_name in match_map.values()
            )

    return ResolvedReceiverModel(
        codeset_id=codeset_id,
        decoder_family_id=decoder_id,
        handlers=handlers,
        match_maps=match_maps,
        event_types=tuple(sorted(event_types)),
    )


def _handlers_for_decoder(
    decoder_id: str | None,
) -> tuple[ReceiveProtocolHandler, ...]:
    """Return handlers in the registered decoder-family order."""
    return PROTOCOL_REGISTRY.handlers_for_family(decoder_id)


def _build_codeset_match_map(
    enum_cls: type[Enum],
    handler: ReceiveProtocolHandler,
) -> dict[CommandMatchKey, str]:
    """Build one protocol-aware match map from a loaded codeset enum."""
    match_map: dict[CommandMatchKey, str] = {}
    for member in enum_cls:
        library_command = _library_member_to_command(member)
        if library_command is None:
            continue

        normalized_command = handler.normalize(library_command)
        if normalized_command is None:
            continue

        existing_command_name = match_map.get(normalized_command.match_key)
        if existing_command_name is None:
            match_map[normalized_command.match_key] = member.name
            continue

        if existing_command_name != member.name:
            _LOGGER.warning(
                "Infrared library codeset %s commands %s and %s share the same "
                "%s identity; retaining %s",
                enum_cls.__name__,
                existing_command_name,
                member.name,
                handler.protocol_id,
                existing_command_name,
            )

    return match_map


def _library_member_to_command(member: Enum) -> Command | None:
    """Return the infrared command generated by a library enum member."""
    to_command = getattr(member, "to_command", None)
    if not callable(to_command):
        return None

    try:
        call_signature = signature(to_command)
    except (TypeError, ValueError):
        _LOGGER.debug(
            "Infrared library command %s does not expose an inspectable to_command",
            member.name,
        )
        return None

    call_kwargs: dict[str, int] = {}
    try:
        call_signature.bind()
    except TypeError:
        try:
            call_signature.bind(repeat_count=0)
        except TypeError:
            _LOGGER.debug(
                "Infrared library command %s does not expose a usable to_command",
                member.name,
            )
            return None

        call_kwargs["repeat_count"] = 0

    try:
        return cast(Command, to_command(**call_kwargs))
    except TypeError as err:
        _LOGGER.warning(
            "Infrared library command %s failed during to_command: %s",
            member.name,
            err,
        )
        return None


def _load_codeset_enum(codeset_id: str) -> type[Enum] | None:
    """Load the enum class for an infrared library codeset."""
    codeset = INFRARED_LIBRARY_CODESETS.get(codeset_id)
    if codeset is None:
        return None

    try:
        enum_cls = getattr(import_module(codeset.module), codeset.enum_class)
    except (ImportError, AttributeError):
        return None

    if not isinstance(enum_cls, type) or not issubclass(enum_cls, Enum):
        return None

    return enum_cls
